name: Memory Leak Check

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  memory-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache Valgrind
      uses: actions/cache@v3
      with:
        path: /usr/bin/valgrind
        key: ${{ runner.os }}-valgrind
        restore-keys: |
          ${{ runner.os }}-valgrind-

    - name: Install Valgrind
      if: steps.cache-valgrind.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind

    - name: Install cargo-valgrind
      run: cargo install cargo-valgrind

    - name: Run memory check with cargo-valgrind
      run: |
        cd rust
        cargo valgrind test -- --nocapture

    - name: Upload Valgrind report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: valgrind-report
        path: rust/valgrind-out.txt
